apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgrespvc
  namespace: mealie
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
