apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-pvc
  namespace: homeassistant
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
