apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: home
  name: home
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
  strategy: {}
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
      - image: homeassistant/home-assistant
        name: home-assistant
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: home-pv
          mountPath: /config   # Mounting the persistent volume here ensures HomeAssistant configs survive Raspberry Pi reboots and pod restarts.
      volumes:
      - name: home-pv
        persistentVolumeClaim:
          claimName: home-pvc
