# ClusterIP Service to expose MariaDB inside the Kubernetes cluster
# Nextcloud (running in the same cluster/namespace) will connect to mariadb.nextcloud.svc.cluster.local:3306
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: nextcloud
spec:
  ports:
  - port: 3306
    name: mysql
  selector:
    app: mariadb
  type: ClusterIP # Internal-only service
