# PVC for MariaDB data directory
# MariaDB stores its database files under /var/lib/mysql — these must persist across pod restarts.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
