apiVersion: v1
kind: Service
metadata:
  name: nextcloudsvc
  namespace: nextcloud
spec:
  selector:
    app: nextcloud
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
