apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nextcloud
  name: nextcloud
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nextcloud
    spec:
      containers:
      - image: nextcloud:apache # The apache tag contains a full Nextcloud installation including an apache web server. This is the default for the latest tag.
        name: nextcloud
        imagePullPolicy: IfNotPresent
        env: # Environment variables - database connection and basic config.
        - name: MYSQL_HOST # This tells Nextcloud where to connect for metadata (users, file index, shares).
          value: mariadb.nextcloud.svc.cluster.local # DNS name of the MariaDB service inside the cluster.
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: MARIADB_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: MARIADB_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: MARIADB_PASSWORD
        volumeMounts:
        - name: nextclouddata-pv
          mountPath: /var/www/html/data # This needs to be the path for any uploads to persist boots and pod restarts. 
        - name: nextcloudconfig-pv
          mountPath: /var/www/html/config # This needs to be the path for Nextcloud settings to persist boots and pod restarts. No need to re-initialize.
      volumes:
      - name: nextclouddata-pv
        persistentVolumeClaim:
          claimName: nextclouddata-pvc
      - name: nextcloudconfig-pv
        persistentVolumeClaim:
          claimName: nextcloudconfig-pvc
        # -------------------------
        # Recommended to add later:
        # - resources.requests/limits to prevent OOM on Pi
        # - livenessProbe/readinessProbe to let Kubernetes manage unhealthy containers
        # - securityContext (runAsUser, fsGroup) so file permissions are consistent
