apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minioconfig-pvc
  namespace: velero
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miniostorage-pvc
  namespace: velero
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
