apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: adguardhome
  name: adguardhome
  namespace: adguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguardhome
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: adguardhome
    spec:
      containers:
      - image: adguard/adguardhome
        name: adguardhome
        volumeMounts:
        - name: adguard-data
          mountPath: /opt/adguardhome/work
      volumes:
      - name: adguard-data
        persistentVolumeClaim:
          claimName: adguard-pvc
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: adguardhome
  name: initialui
  namespace: adguard
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: adguardhome
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: adguardhome
  name: adguardui
  namespace: adguard
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: adguardhome
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: adguardhome
  name: adguarddns
  namespace: adguard
spec:
  ports:
  - port: 53
    name: dns-tcp
    protocol: TCP
    targetPort: 53
  - port: 53
    name: dns-udp
    protocol: UDP
    targetPort: 53
  externalTrafficPolicy: Local
  selector:
    app: adguardhome
  type: LoadBalancer
status:
  loadBalancer: {}
