apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wireguard
  name: wireguardsvc
  namespace: wireguard
spec:
  ports:
  - port: 51820
    protocol: UDP
    name: udp
    targetPort: 51820
  - port: 51821
    protocol: TCP
    name: tcp
    targetPort: 51821
  selector:
    app: wireguard
  type: LoadBalancer
status:
  loadBalancer: {}
