apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wireguard
  name: wgui
  namespace: wireguard
spec:
  ports:
  - port: 30000
    protocol: UDP
    targetPort: wg
  selector:
    app: wireguard
  type: LoadBalancer
status:
  loadBalancer: {}
