alias: Motion Lights On
description: ""
triggers:
  - entity_id: binary_sensor.hue_motion_sensor_1_motion
    to: "on"
    trigger: state
conditions: []
actions:
  - target:
      entity_id: light.led
    action: light.turn_on
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - choose:
      - conditions:
          - condition: time
            after: "06:00:00"
            before: "08:00:00"
        sequence:
          - target:
              entity_id: light.led
            data:
              brightness_pct: 20
              color_temp_kelvin: 2600
            action: light.turn_on
      - conditions:
          - condition: time
            after: "08:00:00"
            before: "09:00:00"
        sequence:
          - target:
              entity_id: light.led
            data:
              brightness_pct: 40
              color_temp_kelvin: 2800
            action: light.turn_on
      - conditions:
          - condition: time
            after: "09:00:00"
            before: "10:00:00"
        sequence:
          - target:
              entity_id: light.led
            data:
              brightness_pct: 70
              color_temp_kelvin: 4000
            action: light.turn_on
      - conditions:
          - condition: time
            after: "10:00:00"
            before: "11:00:00"
        sequence:
          - target:
              entity_id: light.led
            data:
              brightness_pct: 95
              color_temp_kelvin: 4500
            action: light.turn_on
      - conditions:
          - condition: time
            after: "11:00:00"
            before: "17:00:00"
        sequence:
          - target:
              entity_id: light.led
            data:
              brightness_pct: 100
              color_temp_kelvin: 5000
            action: light.turn_on
      - conditions:
          - condition: time
            after: "17:00:00"
            before: "18:00:00"
        sequence:
          - target:
              entity_id: light.led
            data:
              brightness_pct: 95
              color_temp_kelvin: 4500
            action: light.turn_on
      - conditions:
          - condition: time
            after: "18:00:00"
            before: "20:00:00"
        sequence:
          - target:
              entity_id: light.led
            data:
              brightness_pct: 50
              color_temp_kelvin: 3000
            action: light.turn_on
      - conditions:
          - condition: time
            after: "20:00:00"
            before: "21:00:00"
        sequence:
          - target:
              entity_id: light.led
            data:
              brightness_pct: 20
              color_temp_kelvin: 2700
            action: light.turn_on
      - conditions:
          - condition: time
            after: "21:00:00"
            before: "22:00:00"
        sequence:
          - target:
              entity_id: light.led
            data:
              brightness_pct: 15
              color_temp_kelvin: 2600
            action: light.turn_on
      - conditions:
          - condition: time
            after: "22:00:00"
            before: "23:00:00"
        sequence:
          - target:
              entity_id: light.led
            data:
              brightness_pct: 4
              color_temp_kelvin: 2550
            action: light.turn_on
      - conditions:
          - condition: time
            after: "23:00:00"
            before: "06:00:00"
        sequence:
          - target:
              entity_id: light.led
            data:
              brightness_pct: 2
              color_temp_kelvin: 2500
            action: light.turn_on
mode: restart
